src/config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  # Pages
  get "terms-of-service" => "pages#terms_of_service"
  get "privacy-policy" => "pages#privacy_policy"
  get "contact" => "pages#contact"
  get "sitemap" => "pages#sitemap"

  # Sessions
  get "sessions/start"
  delete "signout" => "sessions#signout"
  resources :sessions, except: %i[new create], param: :aid

  # Signup
  get "signup" => "signup#new"
  post "signup" => "signup#create"

  # OAuth
  post "oauth/start" => "oauth#start"
  get "oauth/callback" => "oauth#callback"
  post "oauth/fetch" => "oauth#fetch"

  # Accounts
  resources :accounts, param: :name_id, only: %i[index show]

  # Posts
  resources :posts, param: :name_id

  # Images
  resources :images, param: :aid do
    member do
      post "variants_create" => "images#variants_create", as: "variants_create"
      delete "variants_destroy" => "images#variants_destroy", as: "variants_destroy"
    end
  end

  # Comments
  resources :comments, param: :aid, only: %i[create update]

  # Tags
  resources :tags, param: :name_id

  # Studio
  get "studio" => "studio#index"

  # Settings
  get "settings" => "settings#index"
  get "settings/account" => "settings#account"
  get "settings/icon" => "settings#icon"
  patch "settings/account" => "settings#post_account"
  delete "settings/leave" => "settings#leave"

  # Administorator
  namespace :admin do
    root "studio#index"
    get "studio/console" => "studio#console"
    post "studio/console" => "studio#post_console"
    resources :accounts, param: :aid, only: %i[index edit update]
    patch "posts/update_multiple", to: "posts#update_multiple", as: :update_multiple_posts
    resources :posts, param: :aid, only: %i[index edit update]
    resources :tags, param: :aid, only: [:index]
    resources :comments, param: :aid, only: [:index]
  end

  # API
  namespace :v1 do
    post "images/create" => "images#create"
  end

  # Others
  get "up" => "rails/health#show", as: :rails_health_check

  # Errors
  match "*path", to: "application#routing_error", via: :all
end

src/app/controllers/admin/studio_controller.rb
module Admin
  class StudioController < Admin::ApplicationController
    def index; end

    def console; end

    def post_console
      case params[:command].to_s
      when "recommended_posts_cache_clear"
        Rails.cache.delete('recommended_posts')
        flash.now[:notice] = "Recommended posts cache cleared."
        render :console
      when "all_cache_clear"
        Rails.cache.clear
        flash.now[:notice] = "All cache cleared."
        render :console
      else
        flash.now[:alert] = "Invalid command."
        render :console
      end
    end
  end
end

src/app/controllers/studio_controller.rb
class StudioController < ApplicationController
  before_action :require_signin

  def index
    # 投稿をページングしたい
    @posts = @current_account.posts
      .isnt_deleted
      .order(created_at: :desc)
      .limit(10)
      .includes(:thumbnail)
  end
end

src/app/views/admin/studio/console.html.erb
<h1>Admin Studio Console</h1>

<%= form_with url: admin_studio_console_path, method: :post, local: true, data: { turbo: false } do %>
  <div>
    <%= label_tag :command, 'コマンド' %>
    <%= text_area_tag :command, params[:command], placeholder: 'コマンドを入力してください', rows: 10, cols: 80 %>
  </div>
  <div>
    <%= submit_tag '実行' %>
  </div>
<% end %>

<% if @output.present? %>
  <h2>出力結果</h2>
  <pre><%= @output %></pre>
<% end %>
<% if @error.present? %>
  <h2>エラー</h2>
  <pre><%= @error %></pre>
<% end %>

src/app/views/admin/studio/index.html.erb
<h1>Admin Studio</h1>

<%= link_to('accounts', admin_accounts_path) %>

<%= link_to('posts', admin_posts_path) %>

<%= link_to('images', images_path) %>

<%= link_to('tags', admin_tags_path) %>

<%= link_to('comments', admin_comments_path) %>