src/config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  # Pages
  get "terms-of-service" => "pages#terms_of_service"
  get "privacy-policy" => "pages#privacy_policy"
  get "contact" => "pages#contact"
  get "sitemap" => "pages#sitemap"

  # Sessions
  get "sessions/start"
  delete "signout" => "sessions#signout"
  resources :sessions, except: %i[new create], param: :aid

  # Signup
  get "signup" => "signup#new"
  post "signup" => "signup#create"

  # OAuth
  post "oauth/start" => "oauth#start"
  get "oauth/callback" => "oauth#callback"
  post "oauth/fetch" => "oauth#fetch"

  # Accounts
  resources :accounts, param: :name_id, only: %i[index show]

  # Posts
  resources :posts, param: :name_id

  # Images
  resources :images, param: :aid do
    member do
      post "variants_create" => "images#variants_create", as: "variants_create"
      delete "variants_destroy" => "images#variants_destroy", as: "variants_destroy"
    end
  end

  # Comments
  resources :comments, param: :aid, only: %i[create update]

  # Tags
  resources :tags, param: :name_id

  # Studio
  get "studio" => "studio#index"

  # Settings
  get "settings" => "settings#index"
  get "settings/account" => "settings#account"
  get "settings/icon" => "settings#icon"
  patch "settings/account" => "settings#post_account"
  delete "settings/leave" => "settings#leave"

  # Administorator
  namespace :admin do
    root "studio#index"
    get "studio/console" => "studio#console"
    post "studio/console" => "studio#post_console"
    resources :accounts, param: :aid, only: %i[index edit update]
    patch "posts/update_multiple", to: "posts#update_multiple", as: :update_multiple_posts
    resources :posts, param: :aid, only: %i[index edit update]
    resources :tags, param: :aid, only: [:index]
    resources :comments, param: :aid, only: [:index]
  end

  # API
  namespace :v1 do
    post "images/create" => "images#create"
  end

  # Others
  get "up" => "rails/health#show", as: :rails_health_check

  # Errors
  match "*path", to: "application#routing_error", via: :all
end

src/app/views/pages/contact.html.erb
<% provide(:title, "お問い合わせ") %>

<% if @post %>

  <%= md_render @post.content %>

<% else %>

  <h1>お問い合わせ</h1>

  <p>本サービスのお問い合わせは、下記リンク先に設置しております。</p>

  <a href="https://anyur.com/contact">ANYUR お問い合わせ</a>

<% end %>

src/app/views/pages/index.html.erb
<% provide(:title, "") %>

<% if @current_account %>
  <div>
    <%= link_to("Studio", studio_path, data: { turbo: false }) %>
    <%= link_to("Admin", admin_root_path, data: { turbo: false }) if admin? %>
  </div>
<% end %>

<% if @post %>

  <%= md_render @post.content %>

<% else %>

  <h1>WELCOME TO IVECOLOR</h1>
  <p>kisanaによるブログシステムです。</p>
  <p>特定用途でIDが"index"の投稿を作成し、トップページをカスタマイズできます。</p>

<% end %>

src/app/views/pages/privacy_policy.html.erb
<% provide(:title, "プライバシーポリシー") %>

<% if @post %>

  <%= md_render @post.content %>

<% else %>

  <h1>プライバシーポリシー</h1>

  <p>本サービスのプライバシーポリシーは、下記リンク先に記載しております。</p>

  <a href="https://anyur.com/privacy-policy">ANYUR プライバシーポリシー</a>

<% end %>

src/app/views/pages/sitemap.html.erb
<% provide(:title, "サイトマップ") %>

<% if @post %>

  <%= md_render @post.content %>

<% else %>

  <h1>サイトマップ</h1>

  <ul>
    <li><%= link_to "投稿記事の一覧", posts_path %></li>
    <li><%= link_to "筆者の一覧", accounts_path %></li>
    <li><%= link_to "タグの一覧", tags_path %></li>
  </ul>

  <ul>
    <li><%= link_to "利用規約", terms_of_service_path %></li>
    <li><%= link_to "プライバシーポリシー", privacy_policy_path %></li>
    <li><%= link_to "お問い合わせ", contact_path %></li>
    <li><%= link_to "サイトマップ", sitemap_path %></li>
  </ul>

<% end %>

src/app/views/pages/terms_of_service.html.erb
<% provide(:title, "利用規約") %>

<% if @post %>

  <%= md_render @post.content %>

<% else %>

  <h1>利用規約</h1>

  <p>本サービスの利用規約は、下記リンク先に記載しております。</p>

  <a href="https://anyur.com/terms-of-service">ANYUR 利用規約</a>

<% end %>