src/config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  # Pages
  get "terms-of-service" => "pages#terms_of_service"
  get "privacy-policy" => "pages#privacy_policy"
  get "contact" => "pages#contact"
  get "sitemap" => "pages#sitemap"

  # Sessions
  get "sessions/start"
  delete "signout" => "sessions#signout"
  resources :sessions, except: %i[new create], param: :aid

  # Signup
  get "signup" => "signup#new"
  post "signup" => "signup#create"

  # OAuth
  post "oauth/start" => "oauth#start"
  get "oauth/callback" => "oauth#callback"
  post "oauth/fetch" => "oauth#fetch"

  # Accounts
  resources :accounts, param: :name_id, only: %i[index show]

  # Posts
  resources :posts, param: :name_id

  # Images
  resources :images, param: :aid do
    member do
      post "variants_create" => "images#variants_create", as: "variants_create"
      delete "variants_destroy" => "images#variants_destroy", as: "variants_destroy"
    end
  end

  # Comments
  resources :comments, param: :aid, only: %i[create update]

  # Tags
  resources :tags, param: :name_id

  # Studio
  get "studio" => "studio#index"

  # Settings
  get "settings" => "settings#index"
  get "settings/account" => "settings#account"
  get "settings/icon" => "settings#icon"
  patch "settings/account" => "settings#post_account"
  delete "settings/leave" => "settings#leave"

  # Administorator
  namespace :admin do
    root "studio#index"
    get "studio/console" => "studio#console"
    post "studio/console" => "studio#post_console"
    resources :accounts, param: :aid, only: %i[index edit update]
    patch "posts/update_multiple", to: "posts#update_multiple", as: :update_multiple_posts
    resources :posts, param: :aid, only: %i[index edit update]
    resources :tags, param: :aid, only: [:index]
    resources :comments, param: :aid, only: [:index]
  end

  # API
  namespace :v1 do
    post "images/create" => "images#create"
  end

  # Others
  get "up" => "rails/health#show", as: :rails_health_check

  # Errors
  match "*path", to: "application#routing_error", via: :all
end

src/app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-app-name">
  <%= link_to(ENV['APP_NAME'], root_path) %>
  </div>
  <div class="footer-links">
    <ul>
      <li><%= link_to('利用規約', terms_of_service_path) %></li>
      <li><%= link_to('プライバシーポリシー', privacy_policy_path) %></li>
    </ul>
  </div>
  <div class="footer-actions">
    <ul>
      <li><%= link_to('お問い合わせ', contact_path) %></li>
      <li><%= link_to('サイトマップ', sitemap_path) %></li>
    </ul>
  </div>
</footer>

src/app/views/layouts/_header.html.erb
<header>
  <div class="app-name"><%= link_to(ENV['APP_NAME'], root_path) %></div>
  <nav>
    <div class="nav-link">
      <%= link_to('記事', posts_path) %>
    </div>
    <div class="nav-link">
      <%= link_to('筆者', accounts_path) %>
    </div>
    <div class="nav-link">
      <%= link_to('タグ', tags_path) %>
    </div>
  </nav>
</header>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="content-language" content="ja">
    <title><%= full_title(yield(:title)) %></title>
    <% site_name = ENV['APP_NAME'] %>
    <% author = yield(:author).present? ? yield(:author) : ENV['AUTHOR_NAME'] %>
    <% author_id = yield(:author_id).present? ? yield(:author_id) : ENV['AUTHOR_ID'] %>
    <% type = yield(:type).present? ? yield(:type) : 'website' # website or article %>
    <% robots = yield(:robots).present? ? 'noindex, nofollow' : 'index, follow' %>
    <% image = yield(:image).present? ? yield(:image) : '/img-2.webp' %>
    <% alt = yield(:alt).present? ? yield(:alt) : ENV['APP_NAME'] %>
    <% card = yield(:card).present? ? yield(:card) : 'summary' # summary, summary_large_image, app, player %>
    <meta name="theme-color" content="#ffa9c7" />
    <meta name="color-scheme" content="light" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" href="/img-1.png" type="image/png">
    <meta name="author" content="<%= author %>" />
    <meta name="generator" content="<%= site_name %>" />
    <meta name="description" content="<%= yield(:description) %>" />
    <meta name="keywords" content="<%= yield(:keywords) %>" />
    <meta name="robots" content="<%= robots %>" />
    <meta name="creator" content="<%= author %>" />
    <meta name="googlebot" content="<%= robots %>" />
    <meta name="publisher" content="<%= author %>" />
    <meta name="format-detection" content="email=no,telephone=no,address=no" />
    <meta property="og:url" content="<%= request.path %>" />
    <meta property="og:title" content="<%= yield(:title) %>" />
    <meta property="og:type" content="<%= type %>" />
    <meta property="og:description" content="<%= yield(:description) %>" />
    <meta property="og:image" content="<%= image %>" />
    <meta property="og:locale" content="ja_JP" />
    <meta property="og:site_name" content="<%= site_name %>" >
    <meta name="twitter:card" content="<%= card %>" />
    <meta name="twitter:site" content="<%= site_name %>" />
    <meta name="twitter:site:id" content="<%= author_id %>" />
    <meta name="twitter:title" content="<%= yield(:title) %>" />
    <meta name="twitter:description" content="<%= yield(:description) %>" />
    <meta name="twitter:image" content="<%= image %>" />
    <meta name="twitter:image:alt" content="<%= alt %>" />
    <meta name="twitter:creator" content="<%= author %>" />
    <meta name="twitter:creator:id" content="<%= author_id %>" />
    <meta name="google-adsense-account" content="ca-pub-4578343381731958">
    <meta name="turbo-prefetch" content="false">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield(:head) %>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% if @current_account.nil? && yield(:ga4).blank? && Rails.env.production? %>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4578343381731958" crossorigin="anonymous"></script>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-EMJR3TFCRD"></script>
    <% end %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="wf-roundedmplus1c">
      <div class="main-container">
        <%= yield %>
      </div>
      <% if yield(:layout_style) == 'full'%>
      <div class="sub-container">
        <div class="sub-content">
          <div class="sub-heading">おすすめの記事</div>
          <% recommended_posts().each do |post| %>
            <%= render 'posts/show_mini', post: post %>
          <% end %>
          <div class="sub-heading">新着の記事</div>
          <% new_posts().each do |post| %>
            <%= render 'posts/show_mini', post: post %>
          <% end %>
          <% if @post %>
            <div class="sub-heading">筆者</div>
            <div class="post-account">
              <%= link_to account_path(@post.account.name_id), class: 'post-account-path', data: {turbo_prefetch: false} do %>
                <div class="post-account-top">
                  <div class="post-account-icon-container">
                    <%= image_tag(@post.account.icon_url, class: 'post-account-icon', alt: "#{@post.account.name}のアイコン") %>
                  </div>
                  <div class="post-account-name">
                    <%= @post.account.name %>
                  </div>
                </div>
              <% end %>
            </div>
            <div>
              <%= md_render @post.account.description %>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </main>
    <% flash.each do |message_type, message| %>
      <div class="flash <%= message_type %>"><%= message %></div>
    <% end %>
    <%= render 'layouts/footer' %>
  </body>
</html>